"""Read-only standard-library dashboard through intention prediction."""
import copy, json, threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
LATEST={"payload":None}; LOCK=threading.Lock()
HTML=r'''<!doctype html><html><head><meta charset="utf-8"><title>SUMO Research Evidence</title><style>
*{box-sizing:border-box}body{font:14px system-ui;margin:0;background:#111827;color:#e5e7eb}header{position:sticky;top:0;background:#172033;padding:13px 20px;z-index:3}.meta{display:flex;gap:20px;align-items:center;flex-wrap:wrap}main{padding:16px;max-width:1800px;margin:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(480px,1fr));gap:14px}section,.info{background:#1f2937;border:1px solid #374151;border-radius:9px;padding:14px;overflow:auto;margin-bottom:14px}h2{font-size:17px;margin:0 0 8px;color:#bfdbfe}h3{font-size:15px;color:#c4b5fd}.warn{color:#fbbf24;font-weight:700}.empty,.neutral{color:#9ca3af}.ok{color:#6ee7b7}.bad{color:#fca5a5}.pending{color:#fcd34d}.flow{text-align:center;color:#93c5fd;margin:8px 0 18px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{padding:6px;border-bottom:1px solid #374151;text-align:left;white-space:nowrap}th{color:#93c5fd}.propagated{background:#563719}.observed{background:#123d2b}select{padding:5px}.gates{display:grid;grid-template-columns:1fr auto;gap:7px;max-width:650px}.timeline{position:relative;height:72px;margin:30px 25px 5px;border-top:4px solid #64748b}.mark{position:absolute;top:-13px;transform:translateX(-50%);text-align:center;font-size:11px}.mark:before{content:'';display:block;height:22px;border-left:2px solid #94a3b8;margin:auto}.current{color:#fcd34d;font-weight:800}.current:before{border-color:#fcd34d}.prob{display:grid;grid-template-columns:100px 1fr 60px;gap:6px;margin:5px 0}.bar{background:#374151;border-radius:4px}.fill{height:100%;background:#60a5fa;border-radius:4px}pre{white-space:pre-wrap;font-size:11px}.note{border-left:4px solid #60a5fa;padding-left:10px}
</style></head><body><header><div class="meta"><strong>SUMO Perception to Intention Evidence</strong><span>Time: <b id="time">--</b></span><label>Ego: <select id="ego"></select></label><label>Prediction target: <select id="target"></select></label><span>Approach: <b id="zone">--</b></span><span>Sensor: <b id="sensor">--</b></span></div></header><main><div class="flow">SUMO Ground Truth -> Perception -> Current Output -> LDM -> Prediction Readiness / Timing -> Model Input -> Primary -> Secondary -> Final Intention</div>
<div class="grid"><section><h2>1. SUMO Ground Truth</h2><div class="warn">SIMULATOR GROUND TRUTH - NOT DIRECT EGO KNOWLEDGE</div><div id="gt"></div></section><section><h2>2. Perception Summary + Diagnostics</h2><div id="summary"></div><div id="diag"></div></section><section><h2>3. Current Perception Output</h2><div id="local"></div></section><section><h2>4. Local Dynamic Map</h2><div>Green = observed now; orange = propagated memory.</div><div id="ldm"></div></section></div>
<section><h2>5. Intention Prediction Overview</h2><div id="overview"></div></section><div class="grid"><section><h2>6. Selected Target - Prediction Readiness</h2><div id="readiness"></div></section><section><h2>7. Prediction Timing / ETA Timeline</h2><div id="timing"></div></section></div><section><h2>8. Model Input</h2><div id="model"></div></section><div class="grid"><section><h2 id="primaryTitle">9. Primary Prediction</h2><div id="primary"></div></section><section><h2 id="secondaryTitle">10. Secondary Prediction</h2><div class="note">Later prediction / confirmation stage.</div><div id="secondary"></div></section></div><section><h2>11. Final Intention Fusion</h2><div id="fusion"></div></section><section><h2>12. Two Different Confidence Values</h2><div class="grid"><div><h3>LDM Track Confidence</h3>Freshness/trust of the stored vehicle track.</div><div><h3>Model Prediction Confidence</h3>Maximum LEFT/RIGHT/STRAIGHT model probability.</div></div><p class="warn">LDM track confidence is NOT an input to the GRU intention model.</p><p>ETA triggers prediction timing; it is not one of the six GRU features. Future route truth is not supplied to the predictor.</p></section></main><script>
const $=x=>document.getElementById(x),f=(v,n=2)=>typeof v==='number'?v.toFixed(n):(v??'--'),yn=v=>v?'YES':'NO',xy=v=>Array.isArray(v)?v.map(x=>f(x)).join(', '):'--';let ego='',target='';
function table(rows,cols,cls){if(!rows?.length)return '<div class="empty">No data</div>';return '<table><tr>'+cols.map(c=>'<th>'+c[0]+'</th>').join('')+'</tr>'+rows.map(r=>'<tr class="'+(cls?cls(r):'')+'">'+cols.map(c=>'<td>'+c[1](r)+'</td>').join('')+'</tr>').join('')+'</table>'}
function state(v,neutral){return `<b class="${neutral?'neutral':v?'ok':'bad'}">${neutral?'NOT REACHED':yn(v)}</b>`}function gate(l,v,n){return `<span>${l}</span>${state(v,n)}`}function probs(s){if(!s?.probabilities)return '<div class="neutral">Model has not executed.</div>';return Object.entries(s.probabilities).map(([k,v])=>`<div class="prob"><b>${k}</b><div class="bar"><div class="fill" style="width:${v*100}%"></div></div><span>${f(v*100)}%</span></div>`).join('')}
function stage(name,e,s,c){let p=name.toLowerCase(),reached=e?.[p+'_triggered'];return `<div class="gates">${gate('Trigger reached',reached,!reached)}<span>Trigger time</span><b>${f(e?.[p+'_trigger_time'],3)}</b><span>ETA at trigger</span><b>${f(e?.[p+'_trigger_eta_seconds'])} s</b><span>Distance at trigger</span><b>${f(e?.[p+'_distance_to_entry_meters'])} m</b>${gate('Observed at trigger',e?.[p+'_observed_at_trigger'],!reached)}<span>History at trigger</span><b>${f(e?.[p+'_history_count_at_trigger'],0)} / ${c.required_history_count}</b>${gate('History complete',e?.[p+'_history_complete'],!reached)}${gate('Timing valid',e?.[p+'_history_timing_valid'],!reached)}${gate('Model executed',e?.[p+'_model_executed'],!reached)}<span>Stage status</span><b>${e?.[p+'_stage_status']||'NOT_REACHED'}</b></div>${probs(s)}${s?`<p>Predicted class: <b>${s.predicted_class}</b><br>Confidence: <b>${f(s.confidence,6)}</b><br>Threshold: <b>${f(s.threshold,6)}</b><br>Accepted: <b class="${s.accepted?'ok':'bad'}">${yn(s.accepted)}</b><br>Stage label: <b>${s.label}</b></p>`:''}`}
const fusionText={CONFIRMED_AGREEMENT:'Both accepted horizon predictions agree.',SECONDARY_RECOVERY:'The secondary prediction was accepted after an uncertain primary result.',HORIZON_DISAGREEMENT:'Primary and secondary accepted predictions disagree, so final intention is UNKNOWN.',SECONDARY_UNCERTAIN:'Primary was accepted but the later prediction was uncertain.',BOTH_UNCERTAIN:'Neither horizon prediction passed its confidence threshold.',PRIMARY_MISSING:'The primary result is unavailable.',SECONDARY_MISSING:'The secondary result is unavailable.',BOTH_STAGES_MISSING:'Neither prediction stage produced a result.',WAITING_FOR_FINALIZATION:'The prediction event is still active; the final fused intention is not available yet.'};$('ego').onchange=x=>{ego=x.target.value;target='';render(window.payload)};$('target').onchange=x=>{target=x.target.value;render(window.payload)};
function render(p){if(!p)return;window.payload=p;let c=p.prediction_configuration||{};$('time').textContent=f(p.time_seconds,2)+' s';let es=Object.keys(p.ldm_by_ego||{});if(!es.includes(ego))ego=es[0]||'';$('ego').innerHTML=es.map(x=>`<option ${x===ego?'selected':''}>${x}</option>`).join('');let cards=p.prediction_pipeline_by_ego?.[ego]||[];if(!cards.some(x=>x.target_id===target))target=cards[0]?.target_id||'';$('target').innerHTML=cards.map(x=>`<option ${x.target_id===target?'selected':''}>${x.target_id}</option>`).join('');let card=cards.find(x=>x.target_id===target),e=card?.event||{},pri=e.primary,sec=e.secondary;$('zone').textContent=ego?yn(p.approach_zone_by_ego?.[ego]):'--';$('sensor').textContent=(p.sensor?.profile||'--')+' / '+f(p.sensor?.range_m)+' m';let g=p.ground_truth||{};$('gt').innerHTML='<p>Active vehicles: <b>'+f(g.active_vehicle_count,0)+'</b></p>'+table(g.vehicles,[['Vehicle',r=>r.id],['x',r=>f(r.position?.[0])],['y',r=>f(r.position?.[1])],['Speed',r=>f(r.speed)],['Lane',r=>r.lane_id],['Road',r=>r.road_id]]);let pp=p.perception_by_ego?.[ego]||{};$('summary').innerHTML='<p>'+Object.entries(pp.summary||{}).map(([k,v])=>`${k}: <b>${f(v)}</b>`).join(' | ')+'</p>';$('diag').innerHTML=table(pp.diagnostics,[['Target',r=>r.target_id],['Range',r=>f(r.range_m)],['FOV',r=>f(r.fov_visible_fraction)],['Occlusion',r=>f(r.occlusion_visible_fraction)],['Visible',r=>f(r.visible_fraction)],['Result / reason',r=>(r.result||'--')+' / '+(r.reason||'--')]]);$('local').innerHTML=table(p.local_observations_by_ego?.[ego],[['Target',r=>r.object_id],['Distance',r=>f(r.range)],['Speed',r=>f(r.speed)],['Relative position',r=>xy(r.relative_position_ego)],['Relative velocity',r=>xy(r.relative_velocity_ego)],['Measured',r=>f(r.measurement_timestamp,3)]]);
$('ldm').innerHTML=table(p.ldm_by_ego?.[ego],[['Track',r=>r.id],['Observed',r=>yn(r.is_observed)],['LDM confidence',r=>f(r.confidence)],['Speed',r=>f(r.speed)],['Entry distance',r=>f(r.distance_to_conflict)],['History',r=>r.history_length],['Prediction',r=>{let q=r.intention_prediction;if(!q)return 'WAITING';return `<b>${q.fused_label||q.secondary?.label||q.primary?.label||'WAITING'}</b><br><small>${q.status||'ACTIVE'}</small>`}]],r=>r.is_observed?'observed':'propagated');$('overview').innerHTML=table(cards,[['Target',r=>r.target_id],['Road',r=>r.road_id],['Observed',r=>yn(r.is_observed)],['LDM confidence',r=>f(r.ldm_confidence)],['History',r=>`${r.history_count} / ${r.required_history_count}`],['Readiness',r=>r.history_ready&&r.history_timing_valid?'READY':'NOT READY'],['Entry distance',r=>f(r.distance_to_entry_meters)],['ETA',r=>f(r.estimated_time_to_entry_seconds)],['Event',r=>r.event_state],['Primary',r=>r.primary_stage_status],['Secondary',r=>r.secondary_stage_status],['Intention',r=>r.current_intention],['Status',r=>r.overall_prediction_status]]);
if(!card){['readiness','timing','model','primary','secondary','fusion'].forEach(x=>$(x).innerHTML='<div class="empty">Select an LDM target.</div>');return}$('readiness').innerHTML=`<div class="gates">${gate('Target currently observed',card.is_observed)}${gate('Incoming road',card.incoming_road)}${gate('Relevant to intersection',card.intersection_relevant)}${gate('Prediction event armed',card.event_armed)}<span>History samples</span><b>${card.history_count} / ${card.required_history_count}</b>${gate('History timing valid',card.history_timing_valid)}${gate('Primary trigger reached',card.primary_trigger_reached,!card.event_armed)}${gate('Primary model executed',e.primary_model_executed,!card.primary_trigger_reached)}</div><p class="${card.history_ready&&card.event_armed?'ok':'pending'}">Prediction readiness: ${card.history_ready&&card.event_armed?'READY':'NOT READY / WAITING'}</p>`;let arm=c.event_arming_eta_seconds||1,eta=card.estimated_time_to_entry_seconds,pos=eta==null?null:Math.max(0,Math.min(100,(arm-eta)/arm*100));$('timing').innerHTML=`<p>Simulation: <b>${f(p.time_seconds,2)} s</b> | Distance: <b>${f(card.distance_to_entry_meters)} m</b> | Speed: <b>${f((p.ldm_by_ego?.[ego]||[]).find(x=>x.id===target)?.speed)} m/s</b> | ETA: <b>${f(eta)} s</b></p><div class="timeline"><span class="mark" style="left:0">Armed<br>ETA ${f(arm)}</span><span class="mark" style="left:${(arm-c.primary_lead_time_seconds)/arm*100}%">Primary<br>ETA ${f(c.primary_lead_time_seconds)}</span><span class="mark" style="left:${(arm-c.secondary_lead_time_seconds)/arm*100}%">Secondary<br>ETA ${f(c.secondary_lead_time_seconds)}</span><span class="mark" style="left:100%">Entry<br>ETA 0</span>${pos==null?'':`<span class="mark current" style="left:${pos}%">Current<br>${f(eta)}</span>`}</div>`;
let d=(sec||pri)?.feature_diagnostics;$('model').innerHTML=`<p><b>Source:</b> ${c.required_history_count} genuine LDM position observations<br><b>Sampling:</b> ${f(c.sample_interval_seconds,2)} s / ${f(c.sampling_frequency_hz,0)} Hz<br><b>Observation window:</b> approximately ${f(c.observation_window_seconds,1)} seconds<br><b>Derived sequence:</b> ${c.model_sequence_shape?.[0]} time steps x ${c.model_sequence_shape?.[1]} features</p><ol>${(c.feature_names||[]).map(x=>'<li>'+x.replaceAll('_',' ')+'</li>').join('')}</ol><p class="warn">LDM confidence is NOT a GRU input.</p>${d?table(c.feature_names.map(n=>({n,mean:d.raw_feature_means?.[n],z:d.maximum_absolute_z_score_by_feature?.[n]})),[['Feature',r=>r.n],['Raw mean',r=>f(r.mean,4)],['Maximum absolute z-score',r=>f(r.z,4)]]):'<div class="neutral">Feature diagnostics become available after model execution.</div>'}`;$('primaryTitle').textContent=`9. Primary Prediction - ${f(c.primary_lead_time_seconds,1)} s Horizon`;$('secondaryTitle').textContent=`10. Secondary Prediction - ${f(c.secondary_lead_time_seconds,1)} s Horizon`;$('primary').innerHTML=stage('Primary',e,pri,c);$('secondary').innerHTML=stage('Secondary',e,sec,c);let status=e.status||'WAITING_FOR_FINALIZATION';$('fusion').innerHTML=`<p>Primary label: <b>${pri?.label||'MISSING'}</b><br>Secondary label: <b>${sec?.label||'MISSING'}</b><br>Final fused label: <b>${e.fused_label||'UNKNOWN'}</b><br>Fusion status: <b>${status}</b></p><p>${fusionText[status]||'Status reported directly by the current prediction event.'}</p><details><summary>Technical event details</summary><pre>${JSON.stringify(e,null,2)}</pre></details>`}
async function poll(){try{let r=await fetch('/api/latest',{cache:'no-store'});if(r.ok)render(await r.json())}catch(_e){}setTimeout(poll,1000)}poll();
</script></body></html>'''
class Handler(BaseHTTPRequestHandler):
 def do_GET(self):
  if self.path=="/":self._send(200,"text/html; charset=utf-8",HTML.encode())
  elif self.path=="/api/latest":
   with LOCK:p=copy.deepcopy(LATEST["payload"])
   self._json(200,p or {})
  else:self._json(404,{"error":"not found"})
 def do_POST(self):
  if self.path!="/simulation/update":self._json(404,{"error":"not found"});return
  try:
   n=int(self.headers.get("Content-Length","0"));p=json.loads(self.rfile.read(n))
   with LOCK:LATEST["payload"]=copy.deepcopy(p)
   self._json(202,{"accepted":True})
  except (ValueError,json.JSONDecodeError):self._json(400,{"error":"invalid JSON"})
 def _json(self,s,v):self._send(s,"application/json",json.dumps(v).encode())
 def _send(self,s,t,b):self.send_response(s);self.send_header("Content-Type",t);self.send_header("Content-Length",str(len(b)));self.send_header("Cache-Control","no-store");self.end_headers();self.wfile.write(b)
 def log_message(self,_format,*_args):return
def main():
 server=ThreadingHTTPServer(("localhost",8000),Handler);print("Dashboard: http://localhost:8000")
 try:server.serve_forever()
 except KeyboardInterrupt:pass
 finally:server.server_close()
if __name__=="__main__":main()
