"""Run and report the real Step 5J.3B.3 behavior collection pass."""

from negotiation_training.behavior_rollout import collect_mappo_behavior_rollout


def main():
    result = collect_mappo_behavior_rollout()
    print("\nStep 5J.3B.3 Real MAPPO Behavior Rollout\n")
    print("Readiness")
    print("  Architecture contract complete: PASS")
    print("  Adam contract complete: PASS")
    print("  Configuration unresolved fields: 0")
    print("  Behavior policy readiness: READY_TO_IMPLEMENT_REAL_MAPPO_BEHAVIOR_POLICY\n")
    print("Policy construction")
    print("  Frozen GNN constructed: PASS")
    print("  Proposer actor constructed: PASS")
    print("  Responder actor constructed: PASS")
    print("  Critic constructed: PASS")
    print("  Explicit initialization used: PASS")
    print("  Ambient RNG dependence: False\n")
    print("Behavior identity")
    print(f"  Rollout ID: {result['behavior_rollout_identity']['rollout_id']}")
    print("  Hard-coded training seed: False")
    print(f"  Deterministically derived sampling seed: "
          f"{result['derived_component_seeds']['sampling']}")
    print("  Seed selected by performance: False\n")
    print("TRAINING rollout")
    print("  Manifest passes: 1")
    print(f"  Scenarios attempted: {result['training_scenarios_attempted']}")
    print(f"  Scenarios completed: {result['training_scenarios_completed']}")
    print(f"  Semantic decision batches: {result['joint_decision_batch_count']}")
    print(f"  Proposer PPO factors: {result['proposer_ppo_sample_count']}")
    print(f"  Responder PPO factors: {result['responder_ppo_sample_count']}")
    print(f"  Real proposals: {result['real_proposal_count']}")
    print(f"  Total PPO factors: {result['total_ppo_sample_count']}")
    print(f"  Cyclic outcomes: {result['cyclic_policy_outcome_count']}")
    print(f"  Executable outcomes: {result['executable_policy_outcome_count']}\n")
    print("Safety and objective")
    print(f"  Collisions: {result['collisions']}")
    print(f"  Blocked-zone violations: {result['blocked_zone_violations']}")
    print("  Step 5H reward used: PASS")
    print("  Exact episodic Step 5I returns: PASS")
    print("  Raw centralized advantages: PASS")
    print(f"  Joint critic samples: {result['critic_sample_count']}\n")
    print("PPO integrity")
    print("  Behavior source: MAPPO_BEHAVIOR_POLICY")
    print("  Profiling samples used for PPO: 0")
    print("  Finite old log probabilities: PASS")
    print("  Hard masks replay exactly: PASS")
    print("  Old/current log probabilities exactly equal: PASS")
    print("  Pre-update importance ratios exactly one: PASS")
    print("  Model hashes unchanged: PASS\n")
    print("Research boundary")
    print("  Optimizer instances: 0")
    print("  backward calls: 0")
    print("  Parameter updates: 0")
    print("  PPO optimization epochs executed: 0")
    print("  VALIDATION performance runs: 0")
    print("  HELD_OUT performance runs: 0")
    print("  Learned main.py actions: 0\n")
    print("Status")
    print(f"  STEP_5J_3B_3_STATUS: {result['status']}")
    print(f"  STEP_5J_3B_4_READINESS: {result['step_5j_3b_4_readiness']}")


if __name__ == "__main__": main()
